# Generated by Django 5.0.6 on 2026-09-23 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
