# Generated by Django 5.0.6 on 2026-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('outcome_pending', 'Outcome pending'), ('rented', 'Rented'), ('did_not_rent', 'Did not rent'), ('still_deciding', 'Still deciding'), ('disputed', 'Disputed'), ('rescheduled', 'Rescheduled'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
