# Generated by Django 5.0.6 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0002_alter_viewing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
