# Generated by Django 5.0.6 on 2026-09-23 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
        ('viewings', '0002_alter_viewing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(fields=('viewing',), name='one_dispute_per_viewing'),
        ),
    ]
