# Generated by Django 5.0.6 on 2026-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_savedunit_savedunit_unique_saved_unit_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
