# Generated by Django 5.0.6 on 2026-09-23 17:28

import apps.properties.fields
import django.contrib.postgres.indexes
from django.db import migrations


def copy_coordinates_to_postgis(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "UPDATE properties_property "
        "SET location = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography "
        "WHERE longitude IS NOT NULL AND latitude IS NOT NULL"
    )


def ensure_location_column(apps, schema_editor):
    # Some early installations created this PostGIS column manually to work
    # around the Windows GDAL dependency. Keep those databases migratable.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE properties_property ADD COLUMN IF NOT EXISTS "
            "location geography(Point,4326)"
        )
    else:
        columns = {column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), "properties_property"
        )}
        if "location" not in columns:
            schema_editor.execute('ALTER TABLE "properties_property" ADD COLUMN "location" text')


def restore_coordinates_from_postgis(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "UPDATE properties_property "
        "SET longitude = ST_X(location::geometry), latitude = ST_Y(location::geometry) "
        "WHERE location IS NOT NULL"
    )


def create_location_gist(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            'CREATE INDEX IF NOT EXISTS "properties_location_gist" '
            'ON "properties_property" USING GIST ("location")'
        )


def drop_location_gist(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('DROP INDEX IF EXISTS "properties_location_gist"')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0003_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(ensure_location_column, migrations.RunPython.noop)],
            state_operations=[migrations.AddField(
                model_name='property',
                name='location',
                field=apps.properties.fields.PointField(blank=True, geography=True, null=True, srid=4326),
            )],
        ),
        migrations.RunPython(copy_coordinates_to_postgis, restore_coordinates_from_postgis),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_location_gist, drop_location_gist)],
            state_operations=[migrations.AddIndex(
                model_name='property',
                index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='properties_location_gist'),
            )],
        ),
    ]
