# Generated by Django 5.0.6 on 2026-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_latitude_remove_property_longitude_and_more'),
    ]

    def confirm_existing_availability(apps, schema_editor):
        Unit = apps.get_model('properties', 'Unit')
        Unit.objects.filter(available=True, availability_confirmed_at__isnull=True).update(
            availability_confirmed_at=models.F('updated_at')
        )

    operations = [
        migrations.AddField(
            model_name='unit',
            name='availability_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(confirm_existing_availability, migrations.RunPython.noop),
    ]
