# Generated by Django 5.0.6 on 2026-09-30 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_last4', models.CharField(blank=True, max_length=4)),
                ('role', models.CharField(blank=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('cancelled', 'Cancelled by user'), ('completed', 'Completed'), ('rejected', 'Rejected / retained')], default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms_privacy', 'Terms & Conditions and Privacy Policy'), ('marketing', 'Marketing communications'), ('analytics', 'Optional analytics'), ('location', 'Location-based search')], max_length=20)),
                ('granted', models.BooleanField()),
                ('policy_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='accountdeletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_deletion_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', 'consent_type', '-created_at'], name='consent_user_type_idx'),
        ),
    ]
