# Generated by Django 5.0.6 on 2026-10-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_tenant_viewing_credits'),
        ('properties', '0005_unit_availability_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('referral_fee', 'Landlord referral fee'), ('viewing_credits', 'Tenant viewing credits'), ('verification_fee', 'Property verification fee')], default='referral_fee', max_length=20),
        ),
    ]
